/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  aaa: () => import("@/views/aaa/index.vue"),
  bbb_bbb1: () => import("@/views/bbb/bbb1/index.vue"),
  ccc_ccc1: () => import("@/views/ccc/ccc1/index.vue"),
  ccc: () => import("@/views/ccc/index.vue"),
};
