/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: 'aaa',
    path: '/aaa',
    component: 'layout.base$view.aaa',
    meta: {
      title: 'aaa',
      i18nKey: 'route.aaa'
    }
  },
  {
    name: 'bbb',
    path: '/bbb',
    component: 'layout.base',
    meta: {
      title: 'bbb',
      i18nKey: 'route.bbb'
    },
    children: [
      {
        name: 'bbb_bbb1',
        path: '/bbb/bbb1',
        component: 'view.bbb_bbb1',
        meta: {
          title: 'bbb_bbb1',
          i18nKey: 'route.bbb_bbb1'
        }
      }
    ]
  },
  {
    name: 'ccc',
    path: '/ccc',
    component: 'layout.base',
    meta: {
      title: 'ccc',
      i18nKey: 'route.ccc'
    },
    children: [
      {
        name: 'ccc_ccc1',
        path: '/ccc/ccc1',
        component: 'view.ccc_ccc1',
        meta: {
          title: 'ccc_ccc1',
          i18nKey: 'route.ccc_ccc1'
        }
      }
    ]
  }
];
